name: Elkeid

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build RASP
      uses: docker/build-push-action@v2
      with:
        file: rasp/docker/Dockerfile
        tags: Elkeid/rasp:latest

    - name: Extract RASP
      uses: shrink/actions-docker-extract@v1
      with:
        image: Elkeid/rasp:latest
        path: /Elkeid/rasp/output/.

    - name: Upload RASP
      uses: actions/upload-artifact@v3
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: rasp

    - name: Build Agent
      run: cd agent && go build -o elkeid-agent

    - name: Build Server
      run: cd server/build && ./build.sh