name: Elkeid_plugin_scanner_aarch64

on:
  push:
    branches:
    - main
    - 1.9/scanner

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64, linux/arm64
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Scanner
      uses: docker/build-push-action@v3
      with:
        file: plugins/scanner/docker/Dockerfile.aarch64
        load: true
        tags: elkeid/scanner_aarch64:latest
        context: .
        platforms: linux/arm64

    - name: Extract Scanner
      id: extract-scanner
      uses: shrink/actions-docker-extract@v1
      with:
        image: elkeid/scanner_aarch64:latest
        path: /Elkeid/plugins/scanner/output/.

    - name: Upload Scanner
      uses: actions/upload-artifact@v3
      with:
        path: ${{ steps.extract-scanner.outputs.destination }}
        name: scanner_aarch64